In [107]:
# !pip install brewer2mpl
# import necessary package
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings(action='once')

from IPython import get_ipython
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import Imputer
import tensorflow as tf

In [108]:
import os
cwd = os.getcwd()
cwd

'C:\\Users\\wendy'

In [109]:
#!pip install --upgrade pip

In [110]:
#!pip list

In [111]:
#!pip install --upgrade tensorflow

In [112]:
import tensorflow as tf

In [113]:
pd.set_option('display.max_row',100)
pd.set_option('display.max_column',100)
pd.set_option('display.float_format', lambda x: '%.5f' % x)


large = 22; med = 16; small = 12
params = {'axes.titlesize': large,
          'legend.fontsize': med,
          'figure.figsize': (16, 10),
          'axes.labelsize': med,
          'axes.titlesize': med,
          'xtick.labelsize': med,
          'ytick.labelsize': med,
          'figure.titlesize': large}


plt.rcParams.update(params)
plt.style.use('seaborn-whitegrid')
sns.set_style("white")
#get_ipython().run_line_magic('matplotlib', 'inline')
#exec(%matplotlib inline)
ipy = get_ipython()
if ipy is not None:
    ipy.run_line_magic('matplotlib', 'inline')
# Version
print(mpl.__version__)  #> 3.0.0
print(sns.__version__)  #> 0.9.0

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

3.0.3
0.9.0

In [114]:
data  =  pd.read_csv('C:\\Users\\wendy\Desktop\data.csv')

<>:1: DeprecationWarning: invalid escape sequence \D

In [115]:
data1 = data.iloc[:,1:]
#data2 = data1.drop(['latitude', 'longitude','assessmentyear'], axis = 1)


X_1  =  data1.iloc[:,:-1]
y_1  = data1.iloc[:,-1]

In [116]:
y_1.shape
X_1.columns

Index(['bathroomcnt', 'bedroomcnt', 'buildingqualitytypeid',
       'calculatedfinishedsquarefeet', 'heatingorsystemtypeid', 'latitude',
       'longitude', 'lotsizesquarefeet', 'propertylandusetypeid',
       'rawcensustractandblock', 'regionidcity', 'regionidzip', 'unitcnt',
       'yearbuilt', 'structuretaxvaluedollarcnt', 'assessmentyear',
       'censustractandblock'],
      dtype='object')

In [117]:
X_1.describe()

,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedfinishedsquarefeet,heatingorsystemtypeid,latitude,longitude,lotsizesquarefeet,propertylandusetypeid,rawcensustractandblock,regionidcity,regionidzip,unitcnt,yearbuilt,structuretaxvaluedollarcnt,assessmentyear,censustractandblock
count,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000,214080.00000
mean,0.00044,-0.00056,-0.00031,-0.00441,-0.00539,0.00183,0.00181,-0.00001,0.00958,0.00244,0.00148,-0.00066,-0.00513,0.01039,-0.00331,0.00000,0.00006
std,0.99017,0.99153,0.99057,0.97745,0.96496,1.00114,1.00210,0.97601,0.94351,1.00052,0.98972,0.96902,0.99391,0.99461,0.96423,1.00000,1.00798
min,-2.16653,-2.56387,-2.68958,-1.84685,-0.62427,-3.51475,-2.98457,-0.26197,-38.48223,-1.39379,-0.55486,-0.09101,-0.14941,-5.59173,-0.77991,-1.00021,-0.00581
25%,-0.26098,-0.87248,-1.09162,-0.61493,-0.62427,-0.66434,-0.73743,-0.22317,-0.09015,-0.87091,-0.39862,-0.06079,-0.14941,-0.57787,-0.42334,-1.00021,-0.00477
50%,-0.26098,-0.02678,0.50634,-0.24237,-0.62427,-0.08714,-0.07674,-0.21207,-0.09015,-0.07996,-0.28121,-0.02775,-0.14941,-0.09654,-0.21079,0.99979,-0.00323
75%,0.69179,0.81891,0.50634,0.30741,1.46891,0.38821,0.66821,-0.13350,0.74446,0.59431,0.17980,0.00312,-0.14941,0.78590,0.11114,0.99979,-0.00190
max,16.88888,14.35001,3.16961,22.42745,6.91117,3.29424,2.81197,48.37186,1.24523,2.10659,6.30247,65.92755,216.52823,2.10956,65.53265,0.99979,329.77659

In [118]:
train_X_1, test_X_1, train_y_1, test_y_1 = train_test_split(X_1, y_1, test_size=0.33, random_state=42)
train_set, test_set = train_test_split(data1, test_size=0.33, random_state=42)

In [119]:
train_X_1.shape
train_X_1.head()

,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedfinishedsquarefeet,heatingorsystemtypeid,latitude,longitude,lotsizesquarefeet,propertylandusetypeid,rawcensustractandblock,regionidcity,regionidzip,unitcnt,yearbuilt,structuretaxvaluedollarcnt,assessmentyear,censustractandblock
3113,0.69179,0.81891,0.50634,1.06855,-0.62427,2.69757,0.20573,-0.21337,-0.09015,1.79188,-0.51922,0.19963,-0.14941,1.66834,-0.07624,0.99979,0.00043
58310,-0.26098,-0.02678,-1.09162,0.11632,-0.62427,2.78348,0.90359,-0.22275,-0.09015,1.78908,-0.51922,0.19942,-0.14941,1.70845,-0.33683,-1.00021,0.00043
207640,-0.26098,-0.02678,0.50634,-0.50177,-0.62427,1.48244,-0.97204,-0.22160,-0.09015,1.86768,0.33173,-0.00580,-0.14941,-0.05643,-0.27743,-1.00021,0.00058
61883,-1.21376,-0.87248,-0.55897,-0.50391,0.00000,-0.49980,-0.16973,-0.22755,-0.09015,-0.87012,-0.39862,-0.08318,-0.14941,-2.06197,-0.72282,0.99979,-0.00478
54268,-1.21376,-0.02678,0.50634,-0.61493,1.46891,2.21076,0.88674,-0.21481,-0.09015,1.83010,0.08603,0.20159,-0.14941,-0.33720,-0.59654,-1.00021,0.00051

In [120]:
train_set.shape
train_set.head()

,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedfinishedsquarefeet,heatingorsystemtypeid,latitude,longitude,lotsizesquarefeet,propertylandusetypeid,rawcensustractandblock,regionidcity,regionidzip,unitcnt,yearbuilt,structuretaxvaluedollarcnt,assessmentyear,censustractandblock,logerror
3113,0.69179,0.81891,0.50634,1.06855,-0.62427,2.69757,0.20573,-0.21337,-0.09015,1.79188,-0.51922,0.19963,-0.14941,1.66834,-0.07624,0.99979,0.00043,0.03150
58310,-0.26098,-0.02678,-1.09162,0.11632,-0.62427,2.78348,0.90359,-0.22275,-0.09015,1.78908,-0.51922,0.19942,-0.14941,1.70845,-0.33683,-1.00021,0.00043,-0.01472
207640,-0.26098,-0.02678,0.50634,-0.50177,-0.62427,1.48244,-0.97204,-0.22160,-0.09015,1.86768,0.33173,-0.00580,-0.14941,-0.05643,-0.27743,-1.00021,0.00058,0.09800
61883,-1.21376,-0.87248,-0.55897,-0.50391,0.00000,-0.49980,-0.16973,-0.22755,-0.09015,-0.87012,-0.39862,-0.08318,-0.14941,-2.06197,-0.72282,0.99979,-0.00478,-0.18230
54268,-1.21376,-0.02678,0.50634,-0.61493,1.46891,2.21076,0.88674,-0.21481,-0.09015,1.83010,0.08603,0.20159,-0.14941,-0.33720,-0.59654,-1.00021,0.00051,-0.01055

In [121]:
lr = LinearRegression()
lr.fit(train_X_1, train_y_1[:,np.newaxis])
lr.score(test_X_1, test_y_1)

0.005643889931755464

In [122]:
col_train_bis = list(train_X_1.columns)
feature_cols = [tf.contrib.layers.real_valued_column(k) for k in col_train_bis]

feature_cols

[_RealValuedColumn(column_name='bathroomcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='bedroomcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='buildingqualitytypeid', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='calculatedfinishedsquarefeet', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='heatingorsystemtypeid', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='latitude', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='longitude', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='lotsizesquarefeet', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='propertylandusetypeid', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='rawcensustractandblock', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='regionidcity', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='regionidzip', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='unitcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='yearbuilt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='structuretaxvaluedollarcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='assessmentyear', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='censustractandblock', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)]

In [123]:
FEATURES = col_train_bis
LABEL = "logerror"
train_set.reset_index(drop = True, inplace =True)
def input_fn(data_set, pred = False):
    
    if pred == False:
        
        feature_cols = {k: tf.constant(data_set[k].values) for k in FEATURES}
        labels = tf.constant(data_set[LABEL].values)
        
        return feature_cols, labels

    if pred == True:
        feature_cols = {k: tf.constant(data_set[k].values) for k in FEATURES}
        
        return feature_cols

In [126]:
tf.logging.set_verbosity(tf.logging.ERROR)
'''
DNN = tf.contrib.learn.DNNRegressor(feature_columns=feature_cols, 
                                          activation_fn = tf.nn.relu, hidden_units=[200, 100, 50, 25, 12],
                                         optimizer = tf.train.GradientDescentOptimizer( learning_rate= 0.1 ))
'''

DNN = tf.contrib.learn.DNNRegressor(feature_columns=feature_cols, hidden_units=[10, 10] )

In [127]:
DNN.fit(input_fn=lambda: input_fn(train_set), steps=2000)

DNNRegressor(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._RegressionHead object at 0x00000209AB13B748>, 'hidden_units': [10, 10], 'feature_columns': (_RealValuedColumn(column_name='bathroomcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='bedroomcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='buildingqualitytypeid', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='calculatedfinishedsquarefeet', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='heatingorsystemtypeid', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='latitude', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='longitude', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='lotsizesquarefeet', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='propertylandusetypeid', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='rawcensustractandblock', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='regionidcity', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='regionidzip', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='unitcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='yearbuilt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='structuretaxvaluedollarcnt', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='assessmentyear', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='censustractandblock', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)), 'optimizer': None, 'activation_fn': <function relu at 0x00000209EAF70048>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [129]:
ev = DNN.evaluate(input_fn=lambda: input_fn(test_set), steps=1)

In [130]:
loss_score1 = ev["loss"]
print("Final Loss on the testing set: {0:f}".format(loss_score1))

Final Loss on the testing set: 0.008572

In [134]:
y = DNN.predict(input_fn=lambda: input_fn(test_set))
import itertools
predictions = list(itertools.islice(y, test_set.shape[0]))

In [136]:
mean_squared_error(predictions, test_y_1)

0.008571565974130177

In [137]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
rf = RandomForestRegressor(n_estimators = 200,
                           max_depth = 50,
                          min_samples_split = 20,
                          min_samples_leaf = 4,
                          max_features = 'sqrt')
rf.fit(train_X_1, train_y_1[:,np.newaxis])
pred_y = rf.predict(test_X_1)
mean_squared_error(pred_y, test_y_1)

C:\Users\wendy\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

0.006945244920577023